### ISSUE TITLE
Add gitlab-ci test execution

### ISSUE THREAD

**Issue by aleksandr-kotlyar** [aleksandr-kotlyar/java-sitemap-checker#8]
### Request enhancement
I want to execute this test project in CI as a user, not at local project.
### Possible solution
**GitlabCI** example for maven project:
```yaml
image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master
```
